services:
  kafka-1:
    image: apache/kafka:{{VERSION}}
    ports:
      - "{{PORT}}:{{PORT}}"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:{{PORT}},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:{{PORT}}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_CLUSTER_ID: {{CLUSTER_ID}}

  kafka-2:
    image: apache/kafka:{{VERSION}}
    ports:
      - "{{PORT2}}:{{PORT2}}"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:{{PORT2}},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:{{PORT2}}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_CLUSTER_ID: {{CLUSTER_ID}}

  kafka-3:
    image: apache/kafka:{{VERSION}}
    ports:
      - "{{PORT3}}:{{PORT3}}"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:{{PORT3}},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:{{PORT3}}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: {{REPLICATION_FACTOR}}
      KAFKA_CLUSTER_ID: {{CLUSTER_ID}}